# Generated by Django 3.0.7 on 2020-06-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('pedidos', '0002_auto_20200614_2330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='ProdutoPedido',
        ),
    ]
