# Generated by Django 3.0.4 on 2020-05-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedido_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
