# Generated by Django 3.0.7 on 2020-06-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20200620_1756'),
        ('pedidos', '0003_auto_20200614_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(related_name='produtos', to='pedidos.ProdutoPedido'),
        ),
        migrations.AlterField(
            model_name='produtopedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='produtos.Produto'),
        ),
    ]
