# Generated by Django 3.0.4 on 2020-05-05 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedido_produtos'),
        ('produtos_pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtospedido',
            name='pedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido'),
            preserve_default=False,
        ),
    ]
