# Generated by Django 3.0.6 on 2020-06-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='Bebidas', max_length=255),
            preserve_default=False,
        ),
    ]
