# Generated by Django 3.0.7 on 2020-06-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Salgados', 'Salgados'), ('Sucos', 'Sucos'), ('Bebidas', 'Bebidas')], max_length=255),
        ),
    ]
